spring:
  datasource:
    driver-class-name: org.h2.Driver
    #url: jdbc:h2:file:./foo  ファイルベース
    url: jdbc:h2:mem:foo      #メモリベース
    username: yasuda
    password:
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      INDENT_OUTPUT: true
    property-naming-strategy: SNAKE_CASE
